package org.example.pattern;

public enum PatternType {
    RANDOM,
    INCREMENTAL,
    DECREMENTAL,
    DAILY_SINUSOIDAL,
    WEEKLY_SINUSOIDAL,
    GAUSSIAN_NOISE,
    ANOMALY_SPIKE,
    LINEAR_DRIFT,
    EXPONENTIAL_DECAY,
    RANDOM_WALK,
    MISSING_DATA,
    STEP_FUNCTION,
    SAWTOOTH,
    BURST_EVENT,
    PLATEAU_SHIFT,
    SEASONAL_COMPOSITE,
    CORRELATED
}
